/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import java.awt.Color;
import model.Article;

/**
 *
 * @author Tanja
 */
public class ArticlePanel extends javax.swing.JPanel {
    private Article a;
    private final Color normal;
    /**
     * Creates new form ArticlePanel
     * @param a
     */
    public ArticlePanel(Article a) {
        initComponents();
        this.a = a;
        normal = this.getBackground();
        articleNameLabel.setText(a.getName());
        konsNmbLabel.setText(""+a.getKonsNmb());
    }
    
    public void setSelected(boolean selected) {
        articlePanelCheckBox.setSelected(selected);
        if (selected == true) {
            this.setBackground(Color.BLUE);
        } else {
            this.setBackground(normal);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        articleNameLabel = new javax.swing.JLabel();
        konsNmbLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        articlePanelCheckBox = new javax.swing.JCheckBox();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });

        articleNameLabel.setText("Name");

        konsNmbLabel.setText("KonsNr");

        jLabel1.setText("Kons nr:");

        articlePanelCheckBox.setText("Markér");
        articlePanelCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                articlePanelCheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(articleNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(konsNmbLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(articlePanelCheckBox)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(articleNameLabel)
                    .addComponent(konsNmbLabel)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(articlePanelCheckBox))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void articlePanelCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_articlePanelCheckBoxActionPerformed
        if (articlePanelCheckBox.isSelected() == true) {
            this.setBackground(Color.BLUE);
        } else {
            this.setBackground(normal);
        }
    }//GEN-LAST:event_articlePanelCheckBoxActionPerformed

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        this.setBackground(Color.BLUE);
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        if (articlePanelCheckBox.isSelected() == false) {
            this.setBackground(normal);
        }
    }//GEN-LAST:event_formMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel articleNameLabel;
    private javax.swing.JCheckBox articlePanelCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel konsNmbLabel;
    // End of variables declaration//GEN-END:variables
}
