/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import java.awt.Color;
import java.awt.Component;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import model.Article;
import model.Task;

/**
 *
 * @author Tanja
 */
public class ArticlePanel extends javax.swing.JPanel {
    private Article a;
    private final Color normal;
    private JList taskList;
    private boolean selected;
    /**
     * Creates new form ArticlePanel
     * @param a
     */
    public ArticlePanel(Article a, JList taskList) {
        initComponents();
        this.a = a;
        this.taskList = taskList;
        selected = false;
        normal = this.getBackground();
        articleNameLabel.setText(a.getName());
        konsNmbLabel.setText(""+a.getKonsNmb());
    }

    public Article getA() {
        return a;
    }
    
    public boolean isSelected() {
        return selected;
    }
    
    

    public void setSelected(boolean selected) {
        this.selected = selected;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        articleNameLabel = new javax.swing.JLabel();
        konsNmbLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        articleNameLabel.setText("Name");

        konsNmbLabel.setText("KonsNr");

        jLabel1.setText("Kons nr:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(articleNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(konsNmbLabel)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(articleNameLabel)
                    .addComponent(konsNmbLabel)
                    .addComponent(jLabel1))
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        setBackground(Color.BLUE);
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        if (selected == false) {
            setBackground(normal);
        }
    }//GEN-LAST:event_formMouseExited

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
         if (selected == false) {
            for (Component articlePanel : getParent().getComponents()) {
                ArticlePanel ap = (ArticlePanel) articlePanel;
                if (ap.isSelected()) {
                    ap.setSelected(false);
                    ap.setBackground(normal);
                }
            }
            setBackground(Color.BLUE);
            selected = true;
            ((DefaultListModel)taskList.getModel()).clear();
            if (a.getTasks().size() > 0) {
            for (Task t : a.getTasks()) {
                System.out.println(t.toString());
                ((DefaultListModel)taskList.getModel()).addElement(t);
                taskList.repaint();
                taskList.revalidate();
            }
            }
        } else {
            setBackground(normal);
            selected = false;
        }
    }//GEN-LAST:event_formMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel articleNameLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel konsNmbLabel;
    // End of variables declaration//GEN-END:variables
}
