package view;


import java.awt.CardLayout;
import java.util.Date;
import model.Case;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pdysted
 */
public class CasePanel extends javax.swing.JPanel {
    private GUI gui;
    private CardLayout cl;
    private Case c;
    /**
     * Creates new form CasePanel
     * @param caseNmb the number the case is given
     * @param caseName name of the case
     * @param object name of the object
     * @param createdAt point in time the case was created, this is used for searching too
     */
    public CasePanel(Case c, GUI gui) {
        initComponents();
        this.c = c;
//        caseNameLabel.setText(c.getCaseName());
//        konsNrLabel.setText(""+c.getCaseNmb());
//        //objectLabel.setText();
//        createdAtLabel.setText(""+c.getCreatedAt());
//        cl = gui.getCl();
//        this.gui = gui;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        caseNameLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        konsNrLabel = new javax.swing.JLabel();
        objectLabel = new javax.swing.JLabel();
        createdAtLabel = new javax.swing.JLabel();
        casePanelEditButton = new javax.swing.JButton();

        caseNameLabel.setText("Case name:");

        jLabel1.setText("Kons nr:");

        konsNrLabel.setText("Nr kons");

        objectLabel.setText("Object: ");

        createdAtLabel.setText("CreatedAt");

        casePanelEditButton.setText("Rediger");
        casePanelEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casePanelEditButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(createdAtLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(casePanelEditButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(objectLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(caseNameLabel)
                                .addGap(63, 63, 63)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(konsNrLabel)))
                        .addGap(0, 38, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caseNameLabel)
                    .addComponent(jLabel1)
                    .addComponent(konsNrLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(objectLabel)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(createdAtLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(casePanelEditButton)
                        .addGap(19, 19, 19))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void casePanelEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casePanelEditButtonActionPerformed
//        cl.next(gui.getCardPanel());
//        gui.setC(c);
    }//GEN-LAST:event_casePanelEditButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel caseNameLabel;
    private javax.swing.JButton casePanelEditButton;
    private javax.swing.JLabel createdAtLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel konsNrLabel;
    private javax.swing.JLabel objectLabel;
    // End of variables declaration//GEN-END:variables
}
