/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import javax.swing.JTextField;
import model.Costumer;

/**
 *
 * @author Tanja
 */
public class CustomerPanel extends javax.swing.JPanel {
    //Sikre at kun en kan være selected af gangen
    //eller løb panelerne igennem for at tjekke om en anden er selected
    
    private Costumer c;
    private JTextField[] textFields;
    private boolean selected;
    
    /**
     * Creates new form customerPanel
     *
     * @param c
     */
    public CustomerPanel(Costumer c, JTextField[] textFields) {
        initComponents();
        setBackground(Color.white);
        this.c = c;
        this.textFields = textFields;
        this.selected = false;
        customerNameLabel.setText(c.getCostumerName());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customerNameLabel = new javax.swing.JLabel();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        customerNameLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        customerNameLabel.setText("Kundenavn");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(customerNameLabel)
                .addContainerGap(304, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customerNameLabel)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        if (selected == false) {
        setBackground(Color.BLUE);
        selected = true;
        for (int i = 0; i < textFields.length; i++) {
            switch (i) {
                case 0:
                    textFields[i].setText(c.getCostumerName());
                    break;
                case 1:
                    if (c.getContacts().size() > 0) {
                        textFields[i].setText(c.getContacts().get(0).getConName());
                    } else {
                        textFields[i].setText("");
                    }
                    break;
                case 2:
                    textFields[i].setText("" + c.getPhone());
                    break;
                case 3:
                    textFields[i].setText(c.getEmail());
                    break;
                case 4:
                    textFields[i].setText(c.getAddress());
                    break;

            }
        }
        } else {
            setBackground(Color.WHITE);
            selected = false;
            for (int i = 0; i < textFields.length; i++) {
            switch (i) {
                case 0:
                    textFields[i].setText("");
                    break;
                case 1:
                    textFields[i].setText("");
                    break;
                case 2:
                    textFields[i].setText("");
                    break;
                case 3:
                    textFields[i].setText("");
                    break;
                case 4:
                    textFields[i].setText("");
                    break;
                case 5:
                    textFields[i].setText("");
                    break;

            }
        }
        }
        
    }//GEN-LAST:event_formMousePressed

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        setBackground(Color.BLUE);
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
         if (selected == false) {
            setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_formMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel customerNameLabel;
    // End of variables declaration//GEN-END:variables
}
