/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import interfaces.PanelInterface;
import java.awt.Color;
import model.Costumer;

/**
 *
 * @author Tanja
 */
public class CustomerPanel extends javax.swing.JPanel{
    private Costumer c;
    
    /**
     * Creates new form customerPanel
     * @param c 
     */
    public CustomerPanel(Costumer c) {
        initComponents();
        setBackground(Color.white);
        this.c = c;
        customerNameLabel.setText(c.getCostumerName());
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customerNameLabel = new javax.swing.JLabel();
        selectCustomerButton = new javax.swing.JButton();

        customerNameLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        customerNameLabel.setText("Kundenavn");

        selectCustomerButton.setText("Vælg");
        selectCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectCustomerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(customerNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 237, Short.MAX_VALUE)
                .addComponent(selectCustomerButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(customerNameLabel)
                .addComponent(selectCustomerButton))
        );
    }// </editor-fold>//GEN-END:initComponents
        
    private void selectCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectCustomerButtonActionPerformed

    }//GEN-LAST:event_selectCustomerButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel customerNameLabel;
    private javax.swing.JButton selectCustomerButton;
    // End of variables declaration//GEN-END:variables
}
