/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.CaseHandler;
import java.awt.Color;
import java.awt.Component;
import java.beans.PropertyEditorManager;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Case;
import model.Log;

/**
 *
 * @author pdyst
 */
public class LogWindow extends javax.swing.JPanel {
    private DateFormat dateFormat = new SimpleDateFormat("YYYY/MM/DD HH:mm:ss");
    private ArrayList<Log> logs;
    private Case c;
    private JPanel panel;
    /**
     * Creates new form LogWindow
     */
    public LogWindow(Case c, JPanel panel) {
        initComponents();
        logs = c.getLogs();
        this.c = c;
        this.panel = panel;
        logDisplayTextArea.setEditable(false);
        setBounds(100, 100, 600, 400);
        setBorder(BorderFactory.createLineBorder(Color.black));
        setVisible(true);
        setComponentsVisible(false);
        logCaseNmbLabel.setText(""+c.getKonsNmb()); //Skal erstattes med Case sagsnr i stedet for kons nr
        for (Log log : logs) {
          logDisplayTextArea.append(log.toString() + "\n");
        }
        panel.add(this);
        
    }
    
    public void setComponentsVisible(boolean visible) {
        for (Component comp : panel.getComponents()) {
            comp.setVisible(visible);
            comp.setEnabled(visible);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        logCaseNmbLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        logDisplayTextArea = new javax.swing.JTextArea();
        logPrintButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        jLabel1.setText("Sagsnr:");

        logCaseNmbLabel.setText("sagsnr");

        logDisplayTextArea.setColumns(20);
        logDisplayTextArea.setRows(5);
        jScrollPane1.setViewportView(logDisplayTextArea);

        logPrintButton.setText("Print");
        logPrintButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logPrintButtonActionPerformed(evt);
            }
        });

        backButton.setText("Tilbage");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logCaseNmbLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(backButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logPrintButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(logCaseNmbLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logPrintButton)
                    .addComponent(backButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void logPrintButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logPrintButtonActionPerformed
        
    }//GEN-LAST:event_logPrintButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        setComponentsVisible(true);
        this.setVisible(false);
        panel.remove(this);
        panel.repaint();
        panel.revalidate();
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logCaseNmbLabel;
    private javax.swing.JTextArea logDisplayTextArea;
    private javax.swing.JButton logPrintButton;
    // End of variables declaration//GEN-END:variables
}
